# Generated by Django 5.2.8 on 2025-11-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_room_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['price_per_night']},
        ),
        migrations.RemoveIndex(
            model_name='room',
            name='booking_roo_day_pri_282a15_idx',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='day_price',
            new_name='price_per_night',
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['price_per_night'], name='booking_roo_price_p_88fbfc_idx'),
        ),
    ]
