# Generated by Django 5.2.8 on 2025-11-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['date_start']},
        ),
        migrations.RemoveField(
            model_name='room',
            name='slug',
        ),
    ]
